### ISSUE TITLE
Running command python setup.py egg_info | No CUDA runtime is found ？

### ISSUE THREAD

**Issue by GalaxyHe2023** [OptimalScale/LMFlow#121] opened 2023-04-04 18:14 UTC
++ My cuda version：
C:\Windows\System32>"C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v11.8\bin\nvcc" --version
nvcc: NVIDIA (R) Cuda compiler driver
Copyright (c) 2005-2022 NVIDIA Corporation
Built on Wed_Sep_21_10:41:10_Pacific_Daylight_Time_2022
Cuda compilation tools, release 11.8, V11.8.89
Build cuda_11.8.r11.8/compiler.31833905_0

++ Error about pip install -e . -vvv ：
  Created temporary directory: C:\Users\Administrator\AppData\Local\Temp\pip-pip-egg-info-c7hk02v6
  Running command python setup.py egg_info
  No CUDA runtime is found, using CUDA_HOME='C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v11.8'
  Traceback (most recent call last):
    File "<string>", line 2, in <module>
    File "<pip-setuptools-caller>", line 34, in <module>
    File "C:\Users\Administrator\AppData\Local\Temp\pip-install-o63yw_y4\deepspeed_28a6f2f8ea284f24bfedbef47cfe4ff7\setup.py", line 156, in <module>
      abort(f"Unable to pre-compile {op_name}")
    File "C:\Users\Administrator\AppData\Local\Temp\pip-install-o63yw_y4\deepspeed_28a6f2f8ea284f24bfedbef47cfe4ff7\setup.py", line 48, in abort
      assert False, msg
  AssertionError: Unable to pre-compile async_io

++ Try a long time and can not find the way to fix the issue.

**Comment by research4pan** [comment] 2023-04-04 18:23
Thanks for your attention! This problem can be caused by multiple reasons. You may refer to [this link](https://github.com/open-mmlab/mmdetection/issues/281) for some suggestions. Also, our support for Windows platform is not fully tested yet. You may use Colab or a linux machine first before the support for Windows is ready. Thanks 😄

**Comment by GalaxyHe2023** [comment] 2023-04-05 13:30
I'd be happy to help you test on Windows! Making it compatible with Windows can win you a bunch of new developers since they can use it both at work and at home.

**Comment by GalaxyHe2023** [comment] 2023-04-05 13:53
I try “set CUDA_VISIBLE_DEVICES=0 ” and “set FORCE_CUDA=1”, can not reslove my issue.

**Comment by research4pan** [comment] 2023-04-05 18:36
> AssertionError: Unable to pre-compile async_io

Thanks very much! I checked the error and looks like it is caused by the fact that some Linux library is not supported in Windows, which results in the failure of async_io compilation. According to [this link](https://github.com/microsoft/DeepSpeed/issues/1769#issuecomment-1039098007), one way to walk around is to disable async_io by setting environment variable `DS_BUILD_AIO` to 0.

Hope that can solve your problem.

**Comment by GalaxyHe2023** [comment] 2023-04-06 19:59
I reinstalled the OS, re-downloaded cuda and cudann, made sure my cuda and cudann are both certified.

set DS_BUILD_AIO=0

set DS_BUILD_SPARSE_ATTN=0

Then the error evolved.

No CUDA runtime is found, using CUDA_HOME='E:\00-chatGPT\CUDA'
       The system can not find the file specified.
       The system can not find the file specified.
       The system can not find the file specified.
       The system can not find the file specified.
       fatal: not a git repository (or any of the parent directories): .git
       Traceback (most recent call last):
         File "<string>", line 2, in <module>
         File "<pip-setuptools-caller>", line 34, in <module>
         File "C:\Users\Administrator\AppData\Local\Temp\pip-install-nqtc3o4j\deepspeed_d3894dbfb2fe4c1984b1cd4a0b06e0f7\setup.py", line 198, in <module>
           create_dir_symlink('..\\..\\csrc', '.\\deepspeed\\ops\\csrc')
         File "C:\Users\Administrator\AppData\Local\Temp\pip-install-nqtc3o4j\deepspeed_d3894dbfb2fe4c1984b1cd4a0b06e0f7\setup.py", line 190, in create_dir_symlink
           os. remove(dest)
       PermissionError: [WinError 5] Access is denied. : '.\\deepspeed\\ops\\csrc'

Are there other solutions?

**Comment by research4pan** [comment] 2023-04-07 09:47
```
...
PermissionError: [WinError 5] Access is denied. : '.\deepspeed\ops\csrc'
...
```
Looks like the installed deepspeed cannot be accessed. Could you please check the permission of that file to see if it can be accessed by normal users? Also, you may need administor account to do so. Thanks 😄

**Comment by GalaxyHe2023** [comment] 2023-04-09 13:44
Local windows I think it's not work will. So in deepseed blog find another way, use wsl . The issue was fixed.

**Comment by research4pan** [comment] 2023-04-09 16:21
Thanks for your support and experiments in Windows platform! We will certainly add this to our notes and memorandum. As the issue is fixed, we may close the issue for now. You may feel free to reopen this issue if any new problem is encountered. Thanks 😄

**Closed by research4pan** 2023-04-09 16:21 UTC
