### ISSUE TITLE
error: metadata-generation-failed

### ISSUE THREAD

**Issue by ViktorYoung** [OptimalScale/LMFlow#59] opened 2023-04-02 17:28 UTC
Hello LMFlow Team,

Kudos for your work! 

The error appears while Setup via Git. Could you please let me know any possible way to fix it? 
The code I ran is:
pip install -e .

The error is as follows:
 Traceback (most recent call last):
    File "<string>", line 2, in <module>
    File "<pip-setuptools-caller>", line 34, in <module>
    File "C:\Users\qingd\LMFlow\setup.py", line 24, in <module>
      readme_contents = fp.read().strip()
    File "C:\Users\qingd\anaconda3\envs\lmflow\lib\encodings\cp1252.py", line 23, in decode
      return codecs.charmap_decode(input,self.errors,decoding_table)[0]
  UnicodeDecodeError: 'charmap' codec can't decode byte 0x8f in position 1300: character maps to <undefined>
  [end of output]
  note: This error originates from a subprocess, and is likely not a problem with pip.
error: metadata-generation-failed
Encountered error while generating package metadata.
See above for output.
note: This is an issue with the package mentioned above, not pip.
hint: See above for details.

Best!

**Comment by research4pan** [comment] 2023-04-02 17:42
Thanks for your feedback! It may be caused by the mismatch of default character encoding system. Similar issues have been reported before https://github.com/OptimalScale/LMFlow/issues/51#issuecomment-1493341041, and can be resolved by adding `encoding='utf-8'` in the `open()` function.

**Comment by research4pan** [comment] 2023-04-09 17:12
This issue has been marked as stale because it has not had recent activity. If you think this still needs to be addressed please feel free to reopen this issue. Thanks 😄

**Closed by research4pan** 2023-04-09 17:12 UTC
